# Standard devices
null                 root:root 0666
zero                 root:root 0666
full                 root:root 0666
random               root:root 0666
urandom              root:root 0666
tty                  root:root 0666

# DRM / KMS
dri/card[0-9]+       root:video 0660
dri/renderD[0-9]+    root:video 0660

# Input devices
input/event[0-9]+    root:input 0660
input/mouse[0-9]+    root:input 0660
input/mice           root:input 0660