#!/bin/sh
case "$1" in
  start)
    printf "Loading kernel modules: "
    modprobe brcmfmac
    modprobe bcm2835-codec
    ;;
  stop)
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0
